name: Testing
on:
  pull_request:
    branches:
      - "*"

jobs:
  unit-testing:
    name: Run Unit Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: |
          cd library/
          yarn install --frozen-lockfile
          yarn test:unit-testing:coverage